version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./server
      target: development
    command: npm run start:dev
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
